// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsthxfwyktgdqokdypmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzdGh4Znd5a3RnZHFva2R5cG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMTY2MjIsImV4cCI6MjA2NzU5MjYyMn0.R8oQiiVFiDE25rHKvKL3mH91mQgQaqDSuYJGvsuI4TY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});